name = "values" 
compatibility_date = "2025-04-03"

[pages_build]
# Command to build your project
build_command = "bun run build"
# The directory where your build command puts the built assets (Parcel default is dist)
build_output_dir = "dist" 
